// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.6.0.0
//    <NameSpace>TCDev.SEPA</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><PascalCase>False</PascalCase><BaseClassName>EntityBase</BaseClassName><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net20</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><InitializeFields>All</InitializeFields><GenerateAllTypes>True</GenerateAllTypes>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace TCDev.SEPA.ADMI
{
  using System;
  using System.Diagnostics;
  using System.Xml.Serialization;
  using System.Collections;
  using System.Xml.Schema;
  using System.ComponentModel;
  using System.Collections.Generic;


  [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
  [System.SerializableAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:iso:std:iso:20022:tech:xsd:admi.002.001.01")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:iso:std:iso:20022:tech:xsd:admi.002.001.01", IsNullable = false)]
  public partial class admi_002_001_01
  {

    private admi00200101 admi00200101Field;

    public admi_002_001_01()
    {
      this.admi00200101Field = new admi00200101();
    }

    [System.Xml.Serialization.XmlElementAttribute("admi.002.001.01")]
    public admi00200101 admi00200101
    {
      get
      {
        return this.admi00200101Field;
      }
      set
      {
        this.admi00200101Field = value;
      }
    }
  }

  [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
  [System.SerializableAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(TypeName = "admi.002.001.01", Namespace = "urn:iso:std:iso:20022:tech:xsd:admi.002.001.01")]
  public partial class admi00200101
  {

    private MessageReference rltdRefField;

    private RejectionReason2 rsnField;

    public admi00200101()
    {
      this.rsnField = new RejectionReason2();
      this.rltdRefField = new MessageReference();
    }

    public MessageReference RltdRef
    {
      get
      {
        return this.rltdRefField;
      }
      set
      {
        this.rltdRefField = value;
      }
    }

    public RejectionReason2 Rsn
    {
      get
      {
        return this.rsnField;
      }
      set
      {
        this.rsnField = value;
      }
    }
  }

  [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
  [System.SerializableAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:iso:std:iso:20022:tech:xsd:admi.002.001.01")]
  public partial class MessageReference
  {

    private string refField;

    public string Ref
    {
      get
      {
        return this.refField;
      }
      set
      {
        this.refField = value;
      }
    }
  }

  [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
  [System.SerializableAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:iso:std:iso:20022:tech:xsd:admi.002.001.01")]
  public partial class RejectionReason2
  {

    private string rjctgPtyRsnField;

    private System.Nullable<System.DateTime> rjctnDtTmField;

    private string errLctnField;

    private string rsnDescField;

    private string addtlDataField;

    public string RjctgPtyRsn
    {
      get
      {
        return this.rjctgPtyRsnField;
      }
      set
      {
        this.rjctgPtyRsnField = value;
      }
    }

    public System.DateTime RjctnDtTm
    {
      get
      {
        if (this.rjctnDtTmField.HasValue)
        {
          return this.rjctnDtTmField.Value;
        }
        else
        {
          return default(System.DateTime);
        }
      }
      set
      {
        this.rjctnDtTmField = value;
      }
    }

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RjctnDtTmSpecified
    {
      get
      {
        return this.rjctnDtTmField.HasValue;
      }
      set
      {
        if (value == false)
        {
          this.rjctnDtTmField = null;
        }
      }
    }

    public string ErrLctn
    {
      get
      {
        return this.errLctnField;
      }
      set
      {
        this.errLctnField = value;
      }
    }

    public string RsnDesc
    {
      get
      {
        return this.rsnDescField;
      }
      set
      {
        this.rsnDescField = value;
      }
    }

    public string AddtlData
    {
      get
      {
        return this.addtlDataField;
      }
      set
      {
        this.addtlDataField = value;
      }
    }
  }
}
